/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import org.apache.commons.validator.GenericValidator;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author mateu
 */
public class TelaCategoria extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCategoria.class.getName());

    private static final String URL = "jdbc:postgresql://localhost:5432/lojainformatica";
    private static final String USUARIO = "postgres";
    private static final String SENHA = "postgres";

    /**
     * Creates new form TelaCategoria
     */
    public TelaCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        txtId.setEditable(false);

        tblItens.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting() && tblItens.getSelectedRow() != -1) {
                DefaultTableModel modelo = (DefaultTableModel) tblItens.getModel();
                int linha = tblItens.getSelectedRow();
                txtId.setText(modelo.getValueAt(linha, 0).toString());
                txtNome.setText(modelo.getValueAt(linha, 1).toString());
                txtDescricao.setText(modelo.getValueAt(linha, 2).toString());
            }
        });

        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCadastrar = new javax.swing.JButton();
        txtAtualizar = new javax.swing.JButton();
        txtRemover = new javax.swing.JButton();
        txtLimpar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Descricao");

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descricao"
            }
        ));
        jScrollPane1.setViewportView(tblItens);

        jLabel3.setText("Tela Categoria");

        txtCadastrar.setText("Cadastrar");
        txtCadastrar.addActionListener(this::txtCadastrarActionPerformed);

        txtAtualizar.setText("Atualizar");
        txtAtualizar.addActionListener(this::txtAtualizarActionPerformed);

        txtRemover.setText("Remover");
        txtRemover.addActionListener(this::txtRemoverActionPerformed);

        txtLimpar.setText("Limpar");
        txtLimpar.addActionListener(this::txtLimparActionPerformed);

        jLabel4.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(txtAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRemover)
                .addGap(91, 91, 91)
                .addComponent(txtLimpar)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txtDescricao)
                            .addComponent(txtId)
                            .addComponent(txtCadastrar)
                            .addComponent(jLabel4)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txtCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAtualizar)
                    .addComponent(txtRemover)
                    .addComponent(txtLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_txtCadastrarActionPerformed

    private void txtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtualizarActionPerformed
        atualizar();
    }//GEN-LAST:event_txtAtualizarActionPerformed

    private void txtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemoverActionPerformed
        remover();
    }//GEN-LAST:event_txtRemoverActionPerformed

    private void txtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimparActionPerformed
        limpar();
    }//GEN-LAST:event_txtLimparActionPerformed

    private String validar(String descricao) {
        if (GenericValidator.isBlankOrNull(descricao)) {
            return "Informe a descrição.";
        }

        return null;
    }

    private void cadastrar() {
        String nome = txtNome.getText().trim();
        String descricao = txtDescricao.getText().trim();

        String erro = validar(descricao);
        if (erro != null) {
            javax.swing.JOptionPane.showMessageDialog(this, erro, "Dados inválidos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "INSERT INTO categoria (nome, descricao) VALUES (?, ?)";
        try (Connection conexao = DriverManager.getConnection(URL, USUARIO, SENHA); PreparedStatement pstmt = conexao.prepareStatement(sql)) {
            pstmt.setString(1, nome);
            pstmt.setString(2, descricao);

            pstmt.executeUpdate();

            jLabel9.setText("Categoria \"" + descricao + "\" cadastrada.");
            limpar();
            carregarTabela();
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage(),
                    "Erro de banco de dados", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizar() {
        if (txtId.getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma categoria na tabela primeiro.",
                    "Nenhuma categoria selecionado", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nome = txtNome.getText().trim();
        String descricao = txtDescricao.getText().trim();
        String erro = validar(descricao);
        if (erro != null) {
            javax.swing.JOptionPane.showMessageDialog(this, erro, "Dados inválidos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(txtId.getText());
        String sql = "UPDATE categoria SET nome = ?, descricao = ? WHERE id = ?";
        try (Connection conexao = DriverManager.getConnection(URL, USUARIO, SENHA); PreparedStatement pstmt = conexao.prepareStatement(sql)) {
            pstmt.setString(1, nome);
            pstmt.setString(2, descricao);
            pstmt.setInt(3, id);
            pstmt.executeUpdate();

            jLabel9.setText("Categoria #" + id + " atualizada.");
            limpar();
            carregarTabela();
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(),
                    "Erro de banco de dados", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void remover() {
        if (txtId.getText().isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma categoria na tabela primeiro.",
                    "Nenhuma categoria selecionado", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(txtId.getText());
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this,
                "Remover a categoria \"" + txtDescricao.getText() + "\" (#" + id + ")?",
                "Confirmar remoção", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirmacao != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        String sql = "DELETE FROM categoria WHERE id = ?";
        try (Connection conexao = DriverManager.getConnection(URL, USUARIO, SENHA); PreparedStatement pstmt = conexao.prepareStatement(sql)) {
            pstmt.setInt(1, id);
            pstmt.executeUpdate();

            jLabel9.setText("Categoria #" + id + " removida.");
            limpar();
            carregarTabela();
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao remover: " + e.getMessage(),
                    "Erro de banco de dados", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpar() {
        txtId.setText("");
        txtNome.setText("");
        txtDescricao.setText("");
        tblItens.clearSelection();
        txtDescricao.requestFocus();
    }

    private void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblItens.getModel();
        modelo.setRowCount(0);

        String sql = "SELECT id, nome, descricao FROM categoria ORDER BY id";
        try (Connection conexao = DriverManager.getConnection(URL, USUARIO, SENHA); PreparedStatement pstmt = conexao.prepareStatement(sql); ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id"), rs.getString("nome"), rs.getString("descricao")
                });
            }
            jLabel9.setText(modelo.getRowCount() + " categoria(s) carregada(s).");
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar categorias: " + e.getMessage(),
                    "Erro de banco de dados", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaCategoria dialog = new TelaCategoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItens;
    private javax.swing.JButton txtAtualizar;
    private javax.swing.JButton txtCadastrar;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtId;
    private javax.swing.JButton txtLimpar;
    private javax.swing.JTextField txtNome;
    private javax.swing.JButton txtRemover;
    // End of variables declaration//GEN-END:variables
}
